In [1]:
import torch
import torchvision
import numpy as np


In [71]:
# Load CIFAR10
dataset = torchvision.datasets.CIFAR10(
    root='./',
    transform=torchvision.transforms.ToTensor(),
    download=True)

Files already downloaded and verified


In [72]:
# Get all training targets and count the number of class instances
targets = np.array(dataset.targets) # 长度为10000的list，对应包含data中每一张图片的label
classes, class_counts = np.unique(targets, return_counts=True)
nb_classes = len(classes)
print(class_counts)
print(targets.shape)
print(dataset.data.shape)

[5000 5000 5000 5000 5000 5000 5000 5000 5000 5000]
(50000,)
(50000, 32, 32, 3)


In [73]:
imbal_size = 500
original_size = 5000
# Create artificial imbalanced class counts
imbal_class_counts = [imbal_size, original_size] * 5
# Get class indices
class_indices = [np.where(targets == i)[0] for i in range(nb_classes)]

In [74]:
class_indices

[array([   29,    30,    35, ..., 49941, 49992, 49994], dtype=int64),
 array([    4,     5,    32, ..., 49993, 49998, 49999], dtype=int64),
 array([    6,    13,    18, ..., 49987, 49991, 49995], dtype=int64),
 array([    9,    17,    21, ..., 49979, 49982, 49983], dtype=int64),
 array([    3,    10,    20, ..., 49981, 49984, 49990], dtype=int64),
 array([   27,    40,    51, ..., 49964, 49980, 49988], dtype=int64),
 array([    0,    19,    22, ..., 49962, 49966, 49996], dtype=int64),
 array([    7,    11,    12, ..., 49965, 49978, 49986], dtype=int64),
 array([    8,    62,    69, ..., 49968, 49976, 49985], dtype=int64),
 array([    1,     2,    14, ..., 49963, 49971, 49997], dtype=int64)]

In [75]:
# Get imbalanced number of instances
imbal_class_indices = [class_idx[:class_count] for class_idx, class_count in zip(class_indices, imbal_class_counts)]
imbal_class_indices = np.hstack(imbal_class_indices)    # https://stackoverflow.com/questions/57047417/numpy-hstack-description

In [76]:
imbal_class_indices

array([   29,    30,    35, ..., 49963, 49971, 49997], dtype=int64)

In [77]:
# Set target and data to dataset
dataset.targets = targets[imbal_class_indices]
dataset.data = dataset.data[imbal_class_indices]

assert len(dataset.targets) == len(dataset.data)

In [79]:
dataset.targets.shape

(27500,)

In [80]:
dataset.data.shape

(27500, 32, 32, 3)